### ISSUE TITLE
contactPoint description for PointOfInterest needs correction

### ISSUE THREAD

**Issue by dpatil-fw** [smart-data-models/dataModel.PointOfInterest#10]
In the model:
https://github.com/smart-data-models/dataModel.PointOfInterest/blob/master/PointOfInterest/model.yaml

contactPoint:
      description: 'Contact point for the **museum**.'
      type: Property
      x-ngsi:
        model: https://schema.org/ContactPoint

Since PointOfInterest could be anything based on the 'Category' defined, the above description for contactPoint referring to Museum should be replaced.

**Comment by albertoabellagarcia** [comment]
You're right ... again :-D
fixed.
