### ISSUE TITLE
Id and featuredArtist field under Museum entity

### ISSUE THREAD

**Issue by dpatil-fw** [smart-data-models/dataModel.PointOfInterest#11]
Under https://github.com/smart-data-models/dataModel.PointOfInterest/blob/master/Museum/model.yaml
Looks like content under attribute **featuredArtist** and **id** have got mixed up. See below:

featuredArtist:
      description: 'Main featured artist(s) at this museum.'
      items:
        anyOf:
          - anyOf: &museum_-_properties_-_id_-_anyof
              - description: 'Property. Identifier format of any NGSI entity'
                maxLength: 256
                minLength: 1
                pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
                type: string
              - description: 'Property. Identifier format of any NGSI entity'
                format: uri
                type: string
            description: 'Property. Unique identifier of the entity'
          - type: string
      minItems: 1
      type: Property
      uniqueItems: true
      x-ngsi:
        model: https://schema.org/Person

id:
	anyOf: *museum_-_properties_-_id_-_anyof
	description: 'Unique identifier of the entity'
	type: Property

Also the id is defined as follows for **Store**: "anyOf: &store_-_properties_-_owner_-_items_-_anyof", **PointOfInterest**: "anyOf: &pointofinterest_-_properties_-_owner_-_items_-_anyof", **Beach**: anyOf: &beach_-_properties_-_owner_-_items_-_anyof

So, the id for **Museum** too should start with & instead of *, I assume.
I am not really sure about the relation between id and owner. Will be great if you can mention that as well.

**Comment by albertoabellagarcia** [comment]
id is the unique identifier of every entity inside a context broker 
owner is just an array of url to provide the links with the owner of the entity. 
Featured artist is an array of relationships to the person id of these artists (in case they have it)
