### ISSUE TITLE
Required field for PointOfInterest and Store 

### ISSUE THREAD

**Issue by dpatil-fw** [smart-data-models/dataModel.PointOfInterest#12]
https://github.com/smart-data-models/dataModel.PointOfInterest/blob/master/PointOfInterest/model.yaml
required attributes are mentioned as: 
    - id, - type, - category and - name
Since the name 'Point of Interest' is a geographical indication, shouldn't **location** or address be included as required?

Also for 
https://github.com/smart-data-models/dataModel.PointOfInterest/blob/master/Store/model.yaml
required attributes are mentioned as: 
    - id, - type, - name and - description
Isn't description usually optional? Instead, shouldn't **location** or address be required? 

The following entities have correctly defined location attribute as a required field
https://github.com/smart-data-models/dataModel.PointOfInterest/blob/master/Museum/model.yaml
https://github.com/smart-data-models/dataModel.PointOfInterest/blob/master/Store/model.yaml
required attributes are mentioned as: 
    - id, - type, - location and - name

**Comment by albertoabellagarcia** [comment]
Our policy is to reduce to the minimum the required properties in the data models because for some use cases being mandatory can make sense while in other imposes an artificial restriction preventing the data model to be used. 
The model.yaml, is nice to be reviewed but the official 'source of truth' is the schema.json, and the model.yaml is generated automatically. You can see further explanations in the [contribution_manual](https://bit.ly/contribution_manual)

**Comment by dpatil-fw** [comment]
Thank you for sharing the document, it helped me understand better and to know that schema.json is the source of truth.
Is this document contribution_manual also included in the fiware docs page? If not, will be helpful to do so. On Slide 7 in the document, there is mention of 'All elements will be separated by dot plus space' -> which elements is this referring to?
 
Any specific reason why the 'description' field is 'required' for Store here:  
https://github.com/smart-data-models/dataModel.PointOfInterest/blob/8c6dac3d87429084c1cc4f13e2756f48783196f3/Store/schema.json

Also in the contribution_manual you shared, x-ngsi is defined as a boolean and x-ngsi_text refers to Property, Relationship etc, but it is referred differently in model.yaml - https://github.com/smart-data-models/dataModel.PointOfInterest/blob/master/Store/model.yaml

    areaServed:
      description: 'The geographic area where a service or offered item is provided'
      type: Property
      **x-ngsi:
        model: https://schema.org/Text**

Would be great if you could specify details on what this field **x-ngsi** is and if it is required to be included in a new schema.json.
