### ISSUE TITLE
Extending PointOfInterest 

### ISSUE THREAD

**Issue by dpatil-fw** [smart-data-models/dataModel.PointOfInterest#13]
In this link, https://ngsi-ld-tutorials.readthedocs.io/en/latest/understanding-%40context.html
attributes temperature and fillingLevel are added to Building by specifying allOf Building and the additional two properties.

Why isn't Museum(or Beach or Store) https://raw.githubusercontent.com/smart-data-models/dataModel.PointOfInterest/master/Museum/model.yaml extended from PointOfInterest https://raw.githubusercontent.com/smart-data-models/dataModel.PointOfInterest/master/PointOfInterest/model.yaml similarly with the additional attributes?

**Comment by albertoabellagarcia** [comment]
of course it can be considered if you have a use case we coudl include into the adopters.yaml.

**Comment by dpatil-fw** [comment]
For the solution I am developing, I intend to map various entities like Hospitals, Pharmacies to begin with and later on add Hotel, Restaurants, Stores and Attractions. 

Most of these entities have common attributes - for instance name, description, location, address, website, email, phone, openingHours etc

While I could pick them up directly like this "$ref": "https://smart-data-models.github.io/data-models/common-schema.json#/definitions/GSMA-Commons" and for other attributes:

- {name, description}(GSMA-Commons), 
- {location, address}(Location-Commons), 
- {website, email, phone}(Contact-Commons), 
- openingHours(DateTime-Commons) etc. 

I thought that it would be good to have such common fields all defined in a base PointOfInterest and then simply extend other entities from PointOfInterest instead of including it for every entity separately.

For the use case I described above, do I use existing SmartCity data models and request for changes or do I independently develop them for my private use? What is your suggestion?

Some of the other issues I noticed:

- Museum and Store don't refer openingHours in a uniform way.
- Instead of including contact fields explicitly in various entities, like
"telephone", "email" and "url" explicitly in Store and "contactPoint" for Museum(there is no email and url defined for Museum) would be good to simply include 
"$ref": "https://smart-data-models.github.io/data-models/common-schema.json#/definitions/Contact-Commons" - which contains all contact fields

I have a few other questions on data modelling, should I ask them on StackOverflow or other forum?

**Comment by albertoabellagarcia** [comment]
I guess that current point of interest, quite an old data model, should be extended with contact details, opening hours,etc.
these should be taken as a first option from the [common-schema.json](https://github.com/smart-data-models/data-models/blob/master/common-schema.json) 
Request for changes is welcomed and as long as the request can be applied to general use cases it is likely to be accepted. 
Museum and Store hours, we'll review. 
Fully agree with contact-commons, it should be the default way for data models (bear in mind that these data model have a history), so we are constantly improving
Questions about data models, it is good to be made this way, other more generic can also contact through smartdatamodels.org

**Comment by dpatil-fw** [comment]
Okay, thank you for your response and clarifications.
I have forked the PointOfInterest and will make the first level changes in my repository. Will send the changes for review as per process. 
Another question, it was mentioned that only schema.json is needed and the rest(model.yaml, swagger.yaml etc) is auto-generated. Is this auto-generation tool available in public domain? I wasn't able to find it.

**Comment by albertoabellagarcia** [comment]
The manual contributions now include schema.json, notes.yaml and ADOPTERS.yaml and CONTRIBUTORS.yaml, the rest is automatically generated. LICENSE.md is templated. 
You're right you cannot find the code for no specific reason other than being working on other things (code is not well documented and cleaning them a bit would take the time we are dedicating to increasing functionality)
But you are right that it is one of our pending points. 
But the official place for this script is this [directory](https://github.com/smart-data-models/data-models/tree/master/utils)
