### ISSUE TITLE
Category of this point of interes

### ISSUE THREAD

**Issue by johncaipa** [smart-data-models/dataModel.PointOfInterest#15]
In the category of this point of interest. Allowed values: Those defined by the Factual taxonomy. 
The link to the list of available categories no longer exists, where can we consult this list?

**Comment by albertoabellagarcia** [comment]
we are looking for the replacement of the factual taxonomy, if not available we will remove this mention.

**Comment by albertoabellagarcia** [comment]
Corrected. This resource (or an alternative is no longer available). 
thanks a lot

**Comment by johncaipa** [comment]
@albertoabellagarcia I have always had the question of how to search on SDM website for the available ngsi-ld relationships for each type of entity? For example, for example: if I want to make a relationship between a device and a PointOfInterest, where can I search for the available options?
